### PR TITLE
Updated to comply with POSIX

### PR DESCRIPTION
**Pull request by dkorzhevin**
1. Double quote to prevent globbing and word splitting
2. Use $(...) notation instead of legacy backticked `...`

### CODE REVIEW

**Comment by noptrix** [comment]
@dkorzhevin than you for this! have you tested you changes by any chance?

**Comment by dkorzhevin** [comment]
Hi,

I will be able to test tomorrow. Changes that was applied mostly "cosmetics changes"

**Comment by dkorzhevin** [comment]
Hello,

I've tested changes, and was able to install blackarch, thru installer **does not** asked me to setup X display.

Dmitry

**Comment by noptrix** [comment]
@dkorzhevin thanks for testing. did you see/debug why it did not ask you for X? it should normally

**Comment by dkorzhevin** [comment]
@noptrix I will try to reproduce.

Can you please tell - why my branch has conflicts? Should I re-write it?

**Comment by noptrix** [comment]
@dkorzhevin appologize, completely forgot this issue :) yes, please update your patch now. we've done a lot of changes in the meanwhile.

**Comment by dkorzhevin** [comment]
I will do.

чт, 22 серп. 2019, 11:52 користувач noptrix <notifications@github.com> пише:

**Comment by Edu4rdSHL** [comment]
Hello @dkorzhevin, it can't be merged now, sorry. Most of these problems have been fixed in the [develop branch](https://github.com/BlackArch/blackarch-installer/tree/develop).

Thank you!

**Pull request closed without merging**
