### PR TITLE
installer: adding support for online checksum.

### PR DESCRIPTION
**Pull request by PedroSFreitas**
Following what is proposed in: https://github.com/BlackArch/blackarch-site/pull/84

### CODE REVIEW

**Comment by h0bbl3s** [comment]
screenshot_2018-01-18_17-49-42
This is how I've been doing it. I think theoretically you could have all your checksums in one file, one per line in this format. I absolutely love that you decided to work on this after I mentioned it though :)  :+1:  I think it's a great idea.

**Comment by PedroSFreitas** [comment]
@h0bbl3s Yeah, I could have put all the checksums in a single file. But I think separated are useful as well so it makes it simpler to fetch the information (without filtering it).

**Comment by noptrix** [comment]
thx. will be merged in soon

**Comment by noptrix** [comment]
thx. will be merged in soon

**Pull request merged**
