### PR TITLE
installer: added new security packages

### PR DESCRIPTION
**Pull request by ghost**
Reason for:
dnscrypt-proxy - DNS proxy, with support for encrypted DNS protocols.
fwbuilder - very easy and very fast graphical iptables firewall builder.

### CODE REVIEW

**Comment by noptrix** [comment]
very nice, thank you. will merge in soon. also the other two requests.

**Comment by ghost** [comment]
@noptrix thank you.

**Comment by PH3N1X4C3** [comment]
impressive

**Comment by mrsmith0x00** [comment]
@noptrix P.S. At the moment arch-audit package break installation!

**Comment by noptrix** [comment]
thanks :)

**Pull request merged**
